project_name: sersi

builds:
    - main: ./main.go
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
          - arm64

    - ignore:
          - goos: windows
            goarch: arm64
          - goos: linux
            goarch: arm64

archives:
    - formats:
          - tar.gz
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }"
      format_overrides:
          - goos: windows
            formats:
                - zip

checksum:
    name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
