version: 2
project_name: sersi

before:
    hooks:
        - go mod tidy

builds:
    - main: ./main.go
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
          - arm64

    - ignore:
          - goos: windows
            goarch: arm64
          - goos: linux
            goarch: arm64

archives:
    - formats:
          - tar.gz
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }"
      format_overrides:
          - goos: windows
            formats:
                - zip

release:
    footer: "Copyright 2025 Sersi"

universal_binaries:
    - replace: true
