version: 2

project_name: sersi

before:
    hooks:
        - go mod tidy

builds:
    - main: ./main.go
      goos: [linux, windows, darwin]
      goarch: [amd64, arm64]

archives:
    - formats: ["tar.gz", "zip"]
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
    footer: "Copyright 2025 Sersi"

universal_binaries:
    - replace: true
