version: 2
project_name: sersi

env:
    - SERSI_API_URL={{.Env.SERSI_API_URL}}

builds:
    - id: sersi
      main: ./main.go
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
          - arm64
      ldflags:
          - -s -w -X github.com/sersi-project/sersi/common.Version=v{{ .Version }}
          - -s -w -X github.com/sersi-project/sersi/common.Commit={{ .ShortCommit }}

      ignore:
          - goos: windows
            goarch: arm64
          - goos: linux
            goarch: arm64

archives:
    - format: "tar.gz"
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
      format_overrides:
          - goos: windows
            format: "zip"

checksum:
    name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
