name: "Build"
description: "Action to build Go binaries"
inputs:
    version:
        default: "1.23.4"
runs:
    using: "composite"
    steps:
        - uses: actions/setup-go@v5
          with:
              go-version: { { inputs.version } }
        - run: |
              go mod tidy
              go build -o bin/sersi
              go test ./...
