name: CI/CD Workflow

on:
    push:
        tags:
            - "v*.*.*"
        branches: [main]
    pull_request:
        branches: [main]
        paths:
            - "internal/*"
            - "pkg/*"
            - "cmd/*"
            - ".github/workflows/cicd.yaml"
            - "test/*"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.23.4
            - run: |
                  go mod tidy
                  go build -o bin/sersi
                  go test ./...
            - uses: actions/upload-artifact@v4
              with:
                  name: build-${{github.event.pull_request.head.sha}}
                  path: bin/sersi
    integration-tests:
        needs: build
        if: github.event_name != 'pull_request' || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.23.4
            - run: |
                  go mod tidy
                  ./test/integration-test.sh
    release:
        if: github.event_name == 'push' && github.ref == 'refs/tags/v*.*.*'
        needs: integration-tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.23.4
            - run: |
                  go mod tidy
                  echo "Release not implemented yet"
